force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>직원</label>
    <nameField>
        <displayFormat>EM-{YY}{000}</displayFormat>
        <label>직원번호</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>직원</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EmployeeName__c</fullName>
    <label>직원이름</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/JobLevel__c.field-meta.xml
<CustomField>
    <fullName>JobLevel__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>선임</fullName>
            </value>
            <value>
                <fullName>책임</fullName>
            </value>
            <value>
                <fullName>수석</fullName>
            </value>
            <value>
                <fullName>임원</fullName>
            </value>
            <value>
                <fullName>대표이사</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>입사일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트명</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>프로젝트</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>종료일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>시작일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProjectMember__c/ProjectMember__c.object-meta.xml
<CustomObject>
    <label>프로젝트 멤버</label>
    <nameField>
        <label>프로젝트멤버</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>프로젝트 멤버</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectMember__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>직원</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>ProjectMember</relationshipLabel>
    <relationshipName>ProjectMember_Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectMember__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>ProjectMember</relationshipLabel>
    <relationshipName>ProjectMember_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectMemberBrowser.cls
public with sharing class ProjectMemberBrowser {

    @AuraEnabled(cacheable=true)
    public static List<Employee__c> getEmployee(String projectId) {

        //해당 프로젝트 기간에 프로젝트를 진행하고 있지 않은 직원을 조회해야함
        List<Project__c> listProjects = new List<Project__c>();
        listProjects = [
                SELECT Id, StartDate__c, EndDate__c
                FROM Project__c
                WHERE Id = :projectId
        ];

        Date dateStart = listProjects[0].StartDate__c < Date.today() ? Date.today() : listProjects[0].StartDate__c;
        Date dateEnd = listProjects[0].EndDate__c;

        List<ProjectMember__c> listPM = new List<ProjectMember__c>();
        listPM = [
                SELECT Id, Employee__c
                FROM ProjectMember__c
                WHERE (Project__r.StartDate__c >= :dateStart AND Project__r.StartDate__c <= :dateEnd)
                OR (Project__r.EndDate__c >= :dateStart AND Project__r.EndDate__c <= :dateEnd)
        ];

        Set<Id> setEmployeeIds = new Set<Id>();
        for(ProjectMember__c objPM : listPM){
            setEmployeeIds.add(objPM.Employee__c);
        }

        List<Employee__c> listEmployees = new List<Employee__c>();
        listEmployees = [
                SELECT Id, EmployeeName__c, JobLevel__c
                FROM Employee__c
                WHERE Id NOT IN :setEmployeeIds
                ORDER BY JobLevel__c DESC
        ];
        System.debug('listEmployees :: ' + listEmployees);
        return listEmployees;
    }

}