force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>직원</label>
    <nameField>
        <displayFormat>EM-{YY}{000}</displayFormat>
        <label>직원번호</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>직원</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EmployeeName__c</fullName>
    <label>직원이름</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>입사일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트명</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>프로젝트</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>종료일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>시작일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProjectMember__c/ProjectMember__c.object-meta.xml
<CustomObject>
    <label>프로젝트 멤버</label>
    <nameField>
        <label>프로젝트멤버</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>프로젝트 멤버</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectMember__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>직원</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>ProjectMember</relationshipLabel>
    <relationshipName>ProjectMember_Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectMember__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>역할</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PL</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectMember__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>ProjectMember</relationshipLabel>
    <relationshipName>ProjectMember_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ChangeProjectMemberController.cls
public with sharing class ChangeProjectMemberController {
    
    @AuraEnabled
    public static List<ProjectMember__c> getProjectMembers(String recordId){

        // 현재 프로젝트에 등록된 프로젝트 멤버 조회
        List<ProjectMember__c> listProjectMember = [
            SELECT Id, Name, Position__c, Employee__c, Employee__r.EmployeeName__c
            FROM ProjectMember__c
            WHERE Project__c = :recordId
            ORDER BY Name
        ];

        return listProjectMember;
    }


    @AuraEnabled
    public static List<Employee__c> getAvailableEmployees(){
        Date dateToday = Date.today();

        // 진행 중 프로젝트에 투입된 직원 Id
        Set<Id> setAssigendEmployeeId = new Set<Id>();

        List<ProjectMember__c> listAssignedMember = [
            SELECT Employee__c
            FROM ProjectMember__c
            WHERE Employee__c != null
            AND Project__r.StartDate__c <= :dateToday
            AND Project__r.EndDate__c >= :dateToday
        ];

        for(ProjectMember__c objMember : listAssignedMember) {
            setAssigendEmployeeId.add(objMember.Employee__c);
        }

        // 진행 중 프로젝트에 투입되지 않은 직원
        List<Employee__c> listEmployee = [
            SELECT Id, Name, EmployeeName__c
            FROM Employee__c
            WHERE Id NOT IN :setAssigendEmployeeId
            ORDER BY EmployeeName__c
        ];

        return listEmployee;
    }


    @AuraEnabled
    public static void changeProjectMember(
        String projectMemberId,
        String employeeId
    ){
        // 선택한 프로젝트 멤버의 직원 정보 변경
        ProjectMember__c objProjectMember = new ProjectMember__c(
            Id = projectMemberId,
            Employee__c = employeeId
        );

        // 프로젝트 멤버 업데이트
        update objProjectMember;
    }
}