force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>직원</label>
    <nameField>
        <displayFormat>EM-{YY}{000}</displayFormat>
        <label>직원번호</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>직원</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>EmployeeName__c</fullName>
    <label>직원이름</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트명</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>프로젝트</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectMember__c/ProjectMember__c.object-meta.xml
<CustomObject>
    <label>프로젝트 멤버</label>
    <nameField>
        <label>프로젝트멤버</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>프로젝트 멤버</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectMember__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>직원</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>ProjectMember</relationshipLabel>
    <relationshipName>ProjectMember_Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectMember__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>역할</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PL</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectMember__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>ProjectMember</relationshipLabel>
    <relationshipName>ProjectMember_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectMember_tr.cls
public with sharing class ProjectMember_tr extends TriggerHandler{
    private List<ProjectMember__c> listNew {get; set;}
    
    public ProjectMember_tr() {
        listNew = (list<ProjectMember__c>)Trigger.new;
    }
    
    // 생성되는 프로젝트 멤버의 Name 설정
    public override void beforeInsert(){
        doInsert();
    }
    
    
    
    public void doInsert(){
        
        // 프로젝트와 직원 정보 Id 수집
        Set<Id> projectIdSet = new Set<Id>();
        set<Id> employeeIdSet = new Set<Id>();
        
        for(ProjectMember__c member : listNew){
            if(member.Project__c != null){
                projectIdSet.add(member.Project__c);
            }
            
            if(member.Employee__c != null){
                employeeIdSet.add(member.Employee__c);
            }
        }
        
        System.debug('projectIdSet = ' + projectIdSet);
        System.debug('employeeIdSet = ' + employeeIdSet);
        
        // Id를 기준으로 프로젝트 정보 수집
        Map<Id, Project__c> projectMap =
            new Map<Id, Project__c>([
                Select Id, Name
                From Project__c
                Where Id In :projectIdSet
            ]);
        
        // Id를 기준으로 직원 정보 수집
        Map<Id, employee__c> employeeMap =
            new Map<Id, Employee__c>([
                Select Id, EmployeeName__c
                From Employee__c
                Where Id In :employeeIdSet
            ]);
        
        System.debug('projectMap = ' + projectMap);
        System.debug('employeeMap = ' + employeeMap);


        for(ProjectMember__c member : listNew){
            Project__c project = projectMap.get(member.Project__c);
            Employee__c employee = employeeMap.get(member.Employee__c);

            if(project != null
                && employee != null
                && member.Position__c != null
            ) {
                member.Name = project.Name + '_' +  member.Position__c + '_' + employee.EmployeeName__c;
            }
        }
    }// doInsert() end
}