force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>직원</label>
    <nameField>
        <displayFormat>EM-{YY}{000}</displayFormat>
        <label>직원번호</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>직원</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>입사일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트명</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>프로젝트</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>종료일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>시작일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProjectMember__c/ProjectMember__c.object-meta.xml
<CustomObject>
    <label>프로젝트 멤버</label>
    <nameField>
        <label>프로젝트멤버</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>프로젝트 멤버</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectMember__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>직원</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>ProjectMember</relationshipLabel>
    <relationshipName>ProjectMember_Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectMember__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>역할</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PL</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectMember__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>ProjectMember</relationshipLabel>
    <relationshipName>ProjectMember_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectPmNotice_ba.cls
global with sharing class ProjectPmNotice_ba implements Database.Batchable<SObject> {
    global Database.QueryLocator start(Database.BatchableContext BC){
        // 알림 날짜 계산
        Date DateToday = Date.today();
        Date Date10 = DateToday.addDays(10);    // StartDate__c == Date10 이면 오늘이 10일 전이라는 뜻
        Date Date40 = DateToday.addDays(40);
        Date Date50 = DateToday.addDays(50);
        
        // 알림 대상의 PM 정보 조회
        String strQuery =   'SELECT Id, Project__c, Employee__c, Position__c, ';
        strQuery +=         'Project__r.Name, Project__r.StartDate__c, Project__r.EndDate__c, ';
        strQuery +=         'Employee__r.Name, Employee__r.Email__c ';
        strQuery +=         'FROM ProjectMember__c ';
        strQuery +=         'WHERE Position__c = \'PM\' ';
        strQuery +=         'AND (Project__r.StartDate__c = :Date10 ';
        strQuery +=         'OR Project__r.EndDate__c = :Date40 ';
        strQuery +=         'OR Project__r.EndDate__c = :Date50)';
        
        return Database.getQueryLocator(strQuery);
    }
    global void execute(
        Database.BatchableContext BC,
    List<ProjectMember__c> listTarget
    ) {
        // 발송할 메일 목록
        List<Messaging.SingleEmailMessage> listMail =
            new List<Messaging.SingleEmailMessage>();
        
        // 알림 날짜 계산
        Date DateToday = Date.today();
        Date Date10 = DateToday.addDays(10);    // StartDate__c == Date10 이면 오늘이 10일 전이라는 뜻
        Date Date40 = DateToday.addDays(40);
        Date Date50 = DateToday.addDays(50);
        
        for(ProjectMember__c objProjectMember : listTarget) {
            String strSubject = '';
            String strBody = '';
            
            // 이메일 내용
            if(objProjectMember.Project__r.StartDate__c == Date10){
                strSubject = '[프로젝트 시작 10일 전] ' + objProjectMember.Project__r.Name;
                strBody = objProjectMember.Project__r.Name + ' 프로젝트가 10일 후 시작됩니다.';
            } else if (objProjectMember.Project__r.EndDate__c == Date40) {
                strSubject = '[프로젝트 종료 40일 전] ' + objProjectMember.Project__r.Name;
                strBody = objProjectMember.Project__r.Name + ' 프로젝트가 40일 후 종료됩니다.';
            } else if (objProjectMember.Project__r.EndDate__c == Date50) {
                strSubject = '[프로젝트 종료 50일 전] ' + objProjectMember.Project__r.Name;
                strBody = objProjectMember.Project__r.Name + ' 프로젝트가 50일 후 종료됩니다.';
            }
            
            // PM 이메일이 있는 경우 발송할 메일 구성
            if(
                String.isNotBlank(objProjectMember.Employee__r.Email__c)
                && String.isNotBlank(strSubject)
            ){
                Messaging.SingleEmailMessage objMail = new Messaging.SingleEmailMessage();
                
                objMail.setToAddresses(
                new List<String>{objProjectMember.Employee__r.Email__c}
                );
                
                objMail.setSubject(strSubject);
                objMail.setPlainTextBody(strBody);
                
                listMail.add(objMail);
            }
        } // for문 end
        
        
        // 발송
        if (!listMail.isEmpty()) {
            Messaging.sendEmail(listMail);
        }
        
    }
    global void finish(Database.BatchableContext BC){
        
    }
}