force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트명</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>프로젝트</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>종료일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/IndustryType__c.field-meta.xml
<CustomField>
    <fullName>IndustryType__c</fullName>
    <label>산업분류</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>기술</fullName>
            </value>
            <value>
                <fullName>제조</fullName>
            </value>
            <value>
                <fullName>미디어</fullName>
            </value>
            <value>
                <fullName>제약</fullName>
            </value>
            <value>
                <fullName>기타</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectMemberSearchBar.cls
public with sharing class ProjectMemberSearchBar {

    @AuraEnabled(cacheable=true)
    public static List<String> getIndustryType() {
        List<String> listString = new List<String>();
        listString.add('기술');
        listString.add('제조');
        listString.add('미디어');
        listString.add('제약');
        listString.add('기타');
        return listString;
    }

    @AuraEnabled(cacheable=true)
    public static List<Project__c> getProjectList(String strIndustryType) {
        if (strIndustryType == null || strIndustryType == '') {
            return new List<Project__c>();
        } else {
            List<Project__c> listProjects = [
                    SELECT Id, Name
                    FROM Project__c
                    WHERE IndustryType__c = :strIndustryType
                    AND EndDate__c >= : Date.today()
            ];
            return listProjects;
        }
    }
}