force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>경비</label>
    <nameField>
        <displayFormat>EX-{YY}{MM}{DD}-{0000}</displayFormat>
        <label>경비번호</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>경비</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>경비내용</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>경비</relationshipLabel>
    <relationshipName>Expense_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트명</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>프로젝트</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>종료일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ExpenseInfoDelete_ba.cls
global with sharing class ExpenseInfoDelete_ba implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{

    global Database.QueryLocator start(Database.BatchableContext BC) {
        Date dateSevenMonthAgo = Date.today().addMonths(-7);
        
        // 종료일이 7개월 이상 지난 프로젝트의 경비 조회
        String strQuery = '   SELECT Id ';
        strQuery       += '   FROM   Expense__c';
        strQuery       += '   WHERE Project__r.EndDate__c <= :dateSevenMonthAgo';
        return DataBase.getQueryLocator(strQuery);
    }

    global void execute(Database.BatchableContext BC, List<Expense__c> listTarget){
        System.debug('listTarget >> ' + listTarget);
         try {
            // 조회된 경비의 내용을 비움
            List<Expense__c> listDelete = new List<Expense__c>();
            for(Expense__c exp : listTarget) {
                exp.Description__c = null;
            }
            update listTarget;
            
        }catch(Exception e) {
            System.debug('Error ===================> Error : ' + e.getMessage() + '/' + e.getLineNumber());
        }
    }

    global void finish(Database.BatchableContext BC) {
    }
}