force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>경비</label>
    <nameField>
        <displayFormat>EX-{YY}{MM}{DD}-{0000}</displayFormat>
        <label>경비번호</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>경비</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>경비내용</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>경비</relationshipLabel>
    <relationshipName>Expense_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Spending__c.field-meta.xml
<CustomField>
    <fullName>Spending__c</fullName>
    <label>사용금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트명</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>프로젝트</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PrintExpenseListController.cls
public with sharing class PrintExpenseListController {

    // PDF 페이지 별 경비 목록
    public List<List<Expense__c>> listExpensePage{get; set;}

    public PrintExpenseListController(){
        // URL에서 현재 프로젝트 Id 가져옴
        Id recordId = ApexPages.currentPage().getParameters().get('recordId');

        // 페이지 별 경비 목록 초기화
        listExpensePage = new List<List<Expense__c>>();

        // 현재 프로젝트의 경비 목록 조회
        List<Expense__c> listExpense = [
            SELECT Id, Name, Description__c, Spending__c
            FROM Expense__c
            WHERE Project__c = :recordId
        ];

        // 한 페이지에 들어갈 경비 목록 생성
        List<Expense__c> listPage = new List<Expense__c>();

        for(Integer i = 0; i < listExpense.size(); i++){
            // 20건 마다 새로운 페이지 생성
            if(i != 0 && Math.Mod(i, 20) == 0){
                listExpensePage.add(listPage);
                listPage = new List<Expense__c>();
            }

            listPage.add(listExpense[i]);
        }

        // 마지막 페이지 목록 추가
        listExpensePage.add(listPage);
    }


}