force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>경비</label>
    <nameField>
        <displayFormat>EX-{YY}{MM}{DD}-{0000}</displayFormat>
        <label>경비번호</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>경비</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/UseDate__c.field-meta.xml
<CustomField>
    <fullName>UseDate__c</fullName>
    <label>사용일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ExpenseDateDelete_ba.cls
global with sharing class ExpenseDateDelete_ba implements Database.Batchable<sObject> {
    private Date dateFrom;
    private Date dateTo;
    
    // 시작일과 종료일
    global ExpenseDateDelete_ba(Date dateFrom, Date dateTo) {
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
    }
    
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT Id, UseDate__c
            FROM Expense__c
            WHERE UseDate__c >= :dateFrom
            AND UseDate__c <= :dateTo
        ]);
    }
    
    
    global void execute(Database.BatchableContext BC, List<Expense__c> listTarget) {

        // 조회된 경비가 있으면 삭제
        if (!listTarget.isEmpty()) {
            delete listTarget;
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
}