force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>경비</label>
    <nameField>
        <displayFormat>EX-{YY}{MM}{DD}-{0000}</displayFormat>
        <label>경비번호</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>경비</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>경비</relationshipLabel>
    <relationshipName>Expense_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/UseDate__c.field-meta.xml
<CustomField>
    <fullName>UseDate__c</fullName>
    <label>사용일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트명</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>프로젝트</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/LastExpenseDate__c.field-meta.xml
<CustomField>
    <fullName>LastExpenseDate__c</fullName>
    <label>최근경비사용일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Expense_tr.cls
public with sharing class Expense_tr extends TriggerHandler {
   private List<Expense__c> listNew{get; set;}
   
   public Expense_tr() {
      // 새로운 경비 목록
      listNew = (List<Expense__c>)Trigger.new;
   }
   
   public override void afterInsert(){
      updateLastExpenseDate();
   }
   
   
   public void updateLastExpenseDate(){
      Set<Id> setProjectId = new Set<id>();
      
      for(Expense__c objExpense : listNew){
         if(objExpense.Project__c != null){
            setProjectId.add(objExpense.Project__c);
         }
      }
      
      if(setProjectId.isEmpty()){
         return;
      }
      
      // 프로젝트의 최근경비사용일 조회
      List<Project__c> listProject = [
         select Id, LastExpenseDate__c
         from Project__c
         where Id in :setProjectId
      ];
      
      // 프로젝트별 가장 최근 경비사용일 저장
      Map<Id, Date> mapLastExpenseDate = new Map<Id, Date>();
      
      for(Expense__c objExpense : listNew){
         if(objExpense.Project__c == null || objExpense.UseDate__c == null){
            continue;
         }
         
         // 기존 날짜보다 최신이면 교체
         if(!mapLastExpenseDate.containsKey(objExpense.Project__c)
            || mapLastExpenseDate.get(objExpense.Project__c) < objExpense.UseDate__c
         ){
            mapLastExpenseDate.put(objExpense.Project__c, objExpense.UseDate__c);
         }
      }


      // 기존 최근경비사용일보다 최신일 경우 변경
      List<Project__c> listUpdateProject = new List<Project__c>();

      for(Project__c objProject : listProject){
         Date dateLastExpense = mapLastExpenseDate.get(objProject.Id);

         if(dateLastExpense != null
         && (
            objProject.LastExpenseDate__c == null || objProject.LastExpenseDate__c < dateLastExpense
            )
         ){
            objProject.LastExpenseDate__c = dateLastExpense;
            listUpdateProject.add(objProject);
         }
      }

      // 변경할 프로젝트가 있다면 업데이트
      if(!listProject.isEmpty()){
         update listUpdateProject;
      }
   }
}